site_name: pytspack
theme:
  name: material
nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
